# Generated by Django 3.0.2 on 2020-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20200331_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(default='../static/img/favicon/favicon.png', upload_to='favicon/')),
            ],
        ),
    ]
